spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 10637118752-saheavgti62dc6as7h3oi9vdbo097ol5.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email